//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBuilding
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikedProjects
    {
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> master
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LikedProjects()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int LkdUserId { get; set; }
        public int LkdPrjtId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
<<<<<<< HEAD
=======
=======
        public int LkdUserId { get; set; }
        public int LkdPrjtId { get; set; }
>>>>>>> 0fe1a52926726e58c3d1944c7f290c847d845902
>>>>>>> master
    }
}
